### PR TITLE
Implemented flag counting assist

### PR DESCRIPTION
**Pull request by gtsiam**
Ok, this was supposed to be #1, but oh well. Changes include:
- Added a proper `.gitignore`
- Removed `/docs` and replaced it with a github action. In the github project you'll need to go to `Settings > Code and Automation > Pages > Build and deployment > Source` and choose `Github action` before merging this
- Switched to beta instead of nightly
- Added the `wasm32-unknown-unknown` target to `rust-toolchain.toml`
- Formatted the timer

And finally, the reason I started all this:
- Added an option to count the flags around a cell and subtract it from the displayed neighbouring mines. A flight director instead of an autopilot, if you will.

I have it deployed here: https://gtsiam.github.io/mindsweeper/

### CODE REVIEW

**Comment by gtsiam** [comment]
Also if you're using vscode, try [this](https://marketplace.visualstudio.com/items?itemName=stkb.rewrap) extension to rewrap text. I have no affiliation with it, but it's just that useful.

**Comment by Gurkenglas** [comment]
Nice! I wished for it just before I became aware of this. Can you make the zeroes into empty tiles that immediately expand as though one had clicked on a 0 tile?

**Comment by gtsiam** [comment]
Not too sure about immediately expanding - My goal with this was regular minesweeper just with a visual assist. Though that could be an autopilot setting in the future. I'd have to deal with the menus though, and I've already spent enough time on this. I might come back to it in a few days, but for now I'll leave it as just the visual changes.

That said, I'm not sold on the visuals of 0s everywhere either - originally I had empty tiles instead of 0s, but that was confusing to play since you (where by "you", I mean "I") would often miss the 0 tiles. (Yes, immediately expanding would solve this, but again: I want a flight director, not an autopilot with this).

**Comment by Gurkenglas** [comment]
I think this becoming an autopilot would be fine - as the player improves, they would ideally be presented only with those questions where they need to develop some new technique. If eventually the game hangs because it's stuck in a loop of failing to find more complicated problems to throw at the player, that doesn't sound like a bad outcome.

**Comment by AlexBuz** [comment]
Thank you for the GitHub actions tip and the pull request. This feature is interesting. It seems like it's orthogonal to autopilot because either one can be safely enabled with or without the other?

Someone on Reddit had also asked for flag placement to trigger autopilot. I was thinking of doing that initially but had decided against it because I didn't want placing a flag to be a potentially dangerous operation (since if you misplace a flag then autopilot could reveal a mine) but I might just implement it, since I will admit I have found myself wanting this behavior on occasion too.

**Comment by gtsiam** [comment]
It is actually entirely compatible with autopilot (I've played quite a few games with it on and off): The changes are entirely visual, so they don't affect the gameplay at all. I was just personally tired of counting flags around numbers, so I made the game do it for me.

As a side note, the autopilot probably needs a few switches to turn certain of its features on or off (such as the proposed triggering by flags). Especially as you add more behavior to it.

**Comment by AlexBuz** [comment]
Awesome, it's merged now. I moved the option to the theme config though because it doesn't affect gameplay, just appearance.

**Comment by gtsiam** [comment]
@AlexBuz FYI, you can add things like `.DS_Store` to a global git ignore (say `~/.gitignore`) by setting the `core.excludesfile` git config.

**Pull request merged**
